export const medicationData = [
    'Estradiol Cypionate (Injection)',
    'Estradiol Valerate (Injection)',
    'Estradiol Enanthate (Injection)',
    'Estradiol Sublingual Tablets',
    'Estradiol Oral Tablets',
    'Estradiol Transdermal Patch',
    'Estradiol Gel (Topical)',
    'Estradiol Intranasal Spray',
    'Estradiol Micronized (Oral)',
    'Estradiol Propionate (Injection)',
    'Estrone (Oral Tablet)',
    'Estradiol Buccal Tablet',
    'Estradiol Implant',
    'Estradiol Vaginal Ring',
    'Progesterone (Oral Tablets)',
    'Progesterone Cream (Topical)',
    'Progesterone Injection',
    'Medroxyprogesterone Acetate (Oral Tablet)',
    'Medroxyprogesterone Acetate (Injection)',
    'Dydrogesterone (Oral Tablet)',
    'Norethindrone (Oral Tablet)',
    'Levonorgestrel (Oral Tablet)',
    'Desogestrel (Oral Tablet)',
    'Norethindrone Acetate (Oral Tablet)',
    'Testosterone Cypionate (Injection)',
    'Testosterone Enanthate (Injection)',
    'Testosterone Propionate (Injection)',
    'Testosterone Undecanoate (Oral Capsule)',
    'Testosterone Gel (Topical)',
    'Testosterone Patches (Transdermal)',
    'Testosterone Pellets (Implant)',
    'Testosterone Buccal Tablet',
    'Testosterone Nasal Gel',
    'Testim Gel (Topical)',
    'Androgel (Topical)',
    'Axiron (Topical)',
    'Fortesta (Topical)',
    'Striant (Buccal Tablet)',
    'Depo-Testosterone (Injection)',
    'Delatestryl (Injection)',
    'Testoviron Depot (Injection)',
    'Androderm (Transdermal Patch)',
    'Androgel 1% (Topical)',
    'Testopel (Implant)',
    'Estrogel (Topical Gel)',
    'Estrostep Fe (Oral Tablets)',
    'Climara Pro (Transdermal Patch)',
    'Femring (Vaginal Ring)',
    'Evamist (Transdermal Spray)',
    'Estring (Vaginal Ring)',
    'Vivelle-DOT (Transdermal Patch)',
    'Estradiol Hemihydrate (Topical)',
    'Estradiol Acetate (Oral Tablet)',
    'Testosterone Enanthate 200 mg/ml (Injection)',
    'Testosterone Enanthate 250 mg/ml (Injection)',
    'Testosterone Cypionate 100 mg/ml (Injection)',
    'Testosterone Cypionate 200 mg/ml (Injection)',
    'Testosterone Propionate 25 mg/ml (Injection)',
    'Testosterone Propionate 50 mg/ml (Injection)',
    'Testosterone Undecanoate 120 mg (Oral Capsule)',
    'Testosterone Undecanoate 240 mg (Oral Capsule)',
    'Androgel 1.62% (Topical)',
    'Fortesta 2% (Topical)',
    'Axiron 30 mg (Topical)',
    'Androderm 2 mg (Transdermal Patch)',
    'Androderm 4 mg (Transdermal Patch)',
    'Androgel 1.62% Pump (Topical)',
    'Testopel 75 mg (Implant)',
    'Testopel 150 mg (Implant)',
    'Vivelle (Transdermal Patch)',
    'Estradiol Patch 0.1 mg (Transdermal)',
    'Estradiol Patch 0.2 mg (Transdermal)',
    'Estradiol Patch 0.3 mg (Transdermal)',
    'Estradiol Patch 0.4 mg (Transdermal)',
    'Estradiol Patch 0.5 mg (Transdermal)',
    'Estradiol Patch 0.6 mg (Transdermal)',
    'Estradiol Patch 0.7 mg (Transdermal)',
    'Estradiol Patch 0.8 mg (Transdermal)',
    'Estradiol Patch 0.9 mg (Transdermal)',
    'Estradiol Patch 1.0 mg (Transdermal)',
  ];
  